config/routes.rb
Rails.application.routes.draw do
  resources :puppies
  resources :puppy_rental_requests
end

app/models/puppy.rb
# == Schema Information
#
# Table name: puppies
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Puppy < ActiveRecord::Base

  COLORS = %w(red blue golden chocolate black turquoise)
  SEXES = %w(M F)

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: COLORS
  validates :sex, inclusion: SEXES

  def age
    @age = (Date.today - birth_date).to_i / 365
  end

  has_many :puppy_rental_requests, dependent: :destroy
end

app/models/puppy_rental_request.rb
class PuppyRentalRequest < ActiveRecord::Base

  STATUSES = %w(PENDING APPROVED DENIED)

  validates :puppy_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: STATUSES

  validate :does_not_overlap_with_approved_request

  def does_not_overlap_with_approved_request
    unless overlapping_approved_requests.empty?
      errors[:base] << "Can't overlap with an approved request"
    end
  end
  # def date_range
  #   (start_date..end_date)
  # end

  def overlapping_requests
    self.class.all.select do |request|
      next if request.id == id
      ((start_date - request.end_date) * (request.start_date - end_date) >= 0) && request.puppy_id == puppy_id
    end
    # SQL is hard, dude.
    # PuppyRentalRequest.find_by_sql(
    #   "SELECT
    #     *
    #   FROM
    #     puppy_rental_requests AS other
    #   WHERE
    #     ((DATEDIFF(DAY, #{start_date}, other.end_date) * DATEDIFF(DAY, other.start_date, #{end_date})) >= 0)
    #       AND other.puppy_id = #{puppy_id}") #, start_date, end_date, puppy_id)
  end

  def overlapping_approved_requests
    overlapping_requests.select do |request|
      request.status == "APPROVED"
    end
  end

  belongs_to :puppy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  def index
    @puppies = Puppy.all
    render :index
  end

  def show
    @puppy = Puppy.find(params[:id])

    render :show
  end

  def new
    @puppy = Puppy.new
    render :new
  end

  def edit
    @puppy = Puppy.find(params[:id])
    render :edit
  end

  #We'll fix this stuff later
  
  # def create
  #   @puppy = Puppy.new(puppy_params)
  #
  #   if @puppy.save
  #     redirect_to @puppy
  #   else
  #     render :new
  #   end
  # end

  # def update
  #   @puppy = Puppy.find(params[:id])
  #
  #   if @puppy.update(puppy_params)
  #     redirect_to @puppy
  #   else
  #     render :edit
  #   end
  # end

  private
  def puppy_params
    params.require(:puppy).permit(
      :name,
      :birth_date,
      :color,
      :sex,
      :description
    )
  end

end

app/controllers/puppy_rental_requests_controller.rb
class PuppyRentalRequestsController < ApplicationController
  def new
    @request = PuppyRentalRequest.new
    render :new
  end

  def create
    @request = PuppyRentalRequest.new(request_params)

    if @request.save
      render json: @request
    else
      render json: @request.errors.full_messages
    end
  end

  private
  def request_params
    params.require(:puppy_rental_request).permit(:end_date, :start_date, :puppy_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/puppy_rental_requests_helper.rb
module PuppyRentalRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllThePuppies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<% pped = puppy.persisted? %>

<form action="<%= pped ? puppy_url(puppy) : puppies_url %>"
      method="post">
  <input type="hidden" <%= 'name="_method" value="patch"' if pped %>>

  <label for="puppy_name">Name</label>
  <input type="text"
         id="puppy_name"
         name="puppy[name]"
         value="<%= puppy.name %>">
  </br>

  <label for="puppy_birth_date">Birth Date</label>
  <input type="date"
         id="puppy_birth_date"
         name="puppy[birth_date]"
         value="<%= puppy.birth_date %>">
  </br>

  <label for="puppy_color">Color</label>
  <select name="puppy[color]">
    <%Puppy::COLORS.each do |color|%>
      <option value= "<%=color%>"
              <%= 'selected' if puppy.color == color %>>
        <%=color.capitalize%>
      </option>
    <%end%>
  </select>
  </br>

  <label for="puppy_name">Sex</label>
    <%Puppy::SEXES.each do |sex|%>
      <input type="radio"
             name="puppy[sex]"
             value="<%=sex%>"
             <%= 'checked' if puppy.sex == sex %>>
        <%=sex%>
      </input>
    <%end%>
  </br>

  <label for="puppy_name">Description</label>
  <textarea id="puppy_description"
            name="puppy[description]"><%= puppy.description %></textarea>

  <br/>
  <input type="submit" value="MAKE ME MY PUPPY">
</form>

app/views/puppies/edit.html.erb
<h1>Edit your puppy!</h1>
<h3>Make changes below</h3>

<%= render "form", puppy: @puppy %>

app/views/puppies/index.html.erb
<h1>All the PUPPIES!!!!!</h1>

<ul>
  <% @puppies.each do |puppy| %>
  <li>
    <%= link_to puppy.name, puppy_url(puppy) %>
  </li>
  <% end %>
</ul>

app/views/puppies/new.html.erb
<h1>Make a new puppy!</h1>
<h3>Input details below</h3>

<%= render "form", puppy: @puppy %>

app/views/puppies/show.html.erb
<h1><%= @puppy.name %></h1>

<table>
  <tr>
    <td>name</td>
    <td>color</td>
    <td>age</td>
    <td>sex</td>
    <td>description</td>
  </tr>
  <tr>
    <td><%=@puppy.name%></td>
    <td><%=@puppy.color%></td>
    <td><%=@puppy.age%></td>
    <td><%=@puppy.sex%></td>
    <td><%=@puppy.description%></td>
  </tr>
</table>

app/views/puppy_rental_requests/new.html.erb
<h1>Request a puppy!</h1>

<form action="<%= puppy_rental_requests_url %>"
      method="post">

  <label for="puppy_ids">Pick a puppy</label>
  <select name="puppy_rental_request[puppy_id]">
    <%Puppy.all.each do |puppy|%>
      <option value= "<%=puppy.id%>"
              <%= 'selected' if puppy.id == @request.puppy_id %>>
        <%=puppy.name%>
      </option>
    <%end%>
  </select>
  </br>

  <label for="rental_start_date">Start Date</label>
  <input type="date"
         id="rental_start_date"
         name="puppy_rental_request[start_date]"
         value="<%= @request.start_date %>">
  </br>

  <label for="rental_end_date">End Date</label>
  <input type="date"
         id="rental_end_date"
         name="puppy_rental_request[end_date]"
         value="<%= @request.end_date %>">
  </br>

  <input type="submit" value="RENT ME MY PUPPY">


</form>